name: deploy-staging

on:
  push:
    branches:
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
      - name: Building project
        run: |
          npm install
          npm run build:stag

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy:
      needs: build
      runs-on: Windows
      steps:
        - name: Preparing deploy
          run: xcopy dist firebase_hosting\public /r /e /Y

        - name: Deploy to Firebase
          run: |
            npm install -g firebase-tools
            cd firebase_hosting
            firebase -V
            firebase use --token ${{secrets.FIREBASE_TOKEN}} staging
            firebase deploy --token ${{secrets.FIREBASE_TOKEN}}
